language: cpp

matrix:
  include:
    - os: linux
      name: Linux
      sudo: required
      services: docker
      env: SH="docker exec -t ubuntu-test bash -c"
      before_install:
        - docker run -d --name ubuntu-test -e LC_ALL="en_US.UTF-8" -e LANG="en_US.UTF-8" -v $(pwd):/travis -w /travis ubuntu:latest tail -f /dev/null
      install:
        - $SH "apt-get update"
        - $SH "apt-get install -y locales && locale-gen en_US.UTF-8"
        - $SH "apt-get install -y python3.6-dev cmake build-essential"
      script: $SH "mkdir build && cd build && cmake .. && make && cd .. && PYTHONPATH=my_py_ems ./build/EnergyPlusPyEMS"
    - os: osx
      name: Mac
      script: mkdir build && cd build && cmake .. && make && cd .. && PYTHONPATH=my_py_ems ./build/EnergyPlusPyEMS
    - os: windows
      name: Windows
      install: choco install python3
      script:
        - mkdir build && cd build && cmake .. -G "Visual Studio 15 Win64" && cmake --build . && cd .. # && PYTHONPATH=my_py_ems ./build/Debug/EnergyPlusPyEMS
